--- 
author: 
  email: yugong0391@gmail.com
  github: zhangbinbin
  name: "Binbin Zhang"
  twitter: BinbinSciencist
baseurl: /
copyright: "CC BY-SA 3.0"
description: "Focus on Computer Science,Focus on Human Being! 天,地,人."
excerpt_separator: ""
highlighter: pygments
lsi: false
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"
safe: true
title: "愚公移山,敢为人先"
url: "http://zhangbinbin.tk"