safe: true
lsi: false
author:
name: Binbin Zhang
title: Binbin Zhang
email: yugong0391@gmail.com
description: "Focus on Computer Science,Focus on Human Being! 科技为人类服务,人类为自然服务."
url: http://binzhang.tk
baseurl: /
markdown: kramdown
excerpt_separator: ""
pygments: true
